@eAppointmentServer.WebAPI_HostAddress = http://localhost:5273

POST  http://localhost:5273/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "userNameOrEmail": "admin",
  "password": "1"
}

###
